import type { Metadata } from "next";
import LoginSideLogo from "@/components/common/LoginSideLogo";
import MobileNavBar from "@/components/common/MobileNavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex md:flex-row flex-col w-full min-h-screen overflow-hidden">
      <div className="md:block hidden md:w-[-webkit-fill-available]">
        <LoginSideLogo />
      </div>
      <div className="block md:hidden">
        <MobileNavBar sideBar={false} />
      </div>
      {children}
    </div>
  );
}
